Inclusive wording
alphagov/paas-product-page pull request #144
Opened 2020-03-17 16:47 UTC by paroxp

What
----

We'd like to make sure, people are not discouraged from using the GOV.UK
PaaS. The wording on the signup form, could cause that scenario.

We're adding a little bit wording around how people can get in touch, if
the form is not capable of completing the signup.

How to review
-------------

- Sanity check
- Run locally and test it out

2020-03-17 16:52 UTC, AP-Hunt approved these changes

2020-03-17 17:43 UTC, richardTowers requested changes

2020-03-17 17:43 UTC, richardTowers commented on assets/js/signup.js
> +					This form only accept .gov.uk, .mod.uk, nhs.net, nhs.uk, .police.uk or police.uk email addresses.
```suggestion
					This form only accepts .gov.uk, .mod.uk, nhs.net, nhs.uk, .police.uk or police.uk email addresses.
```

2020-03-17 17:43 UTC, richardTowers commented on views/forms/signup.erb
> +					<%== input_for(@form, :person_email, label: 'Email address', hint: 'Must be from a government or public body') %>
Maybe "government organisation or public body", otherwise it reads a bit like you have to represent a whole Government.

2020-03-17 17:47 UTC, richardTowers approved these changes

2020-03-18 08:21 UTC, tlwr approved these changes

2020-03-18 08:21 UTC, merged